mqtt:
  server: "10.1.0.25"
  port: 1883
  username: "mqtt"
  password: "mqtt1234"
sterbox:
  name: "sterbox2"
  url: "10.1.0.181"
  password: "1234"
  interval: 1
  rest_delay: 1  # opóźnienie 1000ms między zapytaniami REST, można zmieniać
debug: true  # ustawienie false wyłączy wyświetlanie informacji na konsoli
variables:
  parm1:
    tempk: "@gca?temp_k&"
    stat24dn: "@gcd?stat24dn&"
    stat24up: "@gcd?stat24up&"
  parm2:
    RO21: "@gcd?RO21up&"
    RO22: "@gcd?RO22up&"
