# config.yaml
mqtt:
  server: "10.1.0.25"
  port: 1883
  username: "mqtt"
  password: "mqtt1234"

sterbox:
  name: "sterbox2"
  url: "10.1.0.181"
  password: "1234"
  interval: 0.1  # jak często publikować dane przez MQTT (w sekundach)
  rest_delay: 2.0  # opóźnienie między zapytaniami do różnych sekcji (w sekundach)
  max_connection_retries: 5  # maksymalna liczba prób ponownego połączenia
  connection_retry_delay: 5  # opóźnienie między próbami połączenia (w sekundach)
  
debug: true  # ustawienie true włączy wyświetlanie informacji diagnostycznych

variables:
  parm1:
    tempk: "@gca?temp_k&"
    stat24dn: "@gcd?stat24dn&"
    stat24up: "@gcd?stat24up&"
  parm2:
    RO21: "@gcd?RO21up&"
    RO22: "@gcd?RO22up&"
